### ISSUE TITLE
在mac air 中无法搜索到android emulator模拟器

### ISSUE THREAD

**Issue by hmbool** [MaaXYZ/MaaDebugger#12]
MaaFw version 1.8.9
python version 3.12.4
macos version 15.1 beta 
[maa.log](https://github.com/user-attachments/files/16467963/maa.log)

<img width="434" alt="image" src="https://github.com/user-attachments/assets/e1a373f9-331f-4f9d-b352-3fabca87b222">
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/88e629cd-d835-4b14-bffc-db17e4484685">
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/cc445b2a-3a2a-4e89-b9e2-e6ca1af10039">

如何搜索？还是需要其他模拟器？

**Comment by MistEO** [comment]
绑定到非 localhost 是没法搜到的（

手动填了能连上吗？

**Comment by MistEO** [comment]
你截图里 adb 填的不对，要填到 exec 而不是 dir

**Comment by hmbool** [comment]
> 绑定到非 localhost 是没法搜到的（
> 
> 手动填了能连上吗？
adb位置也改了，改了手动可以了
我用mumupro可以adb连接成功了
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/18cf91a1-bf30-4314-b60f-f4b7b4a8fa0e">
