### ISSUE TITLE
nicegui未能加载识别结果list

### ISSUE THREAD

**Issue by xiaofeiTM233** [MaaXYZ/MaaDebugger#20]
已尝试更新到maadebugger最新版，无变化
module 'nicegui.ui' has no attribute 'list'
![image](https://github.com/user-attachments/assets/82cb23b4-16d4-4b4f-a24a-173fbd4877cb)
![image](https://github.com/user-attachments/assets/aa2df9bd-441b-4eef-9740-ea1f0e09ca4e)

**Comment by MistEO** [comment]
用的什么版本的 nicegui？

**Comment by xiaofeiTM233** [comment]
> 用的什么版本的 nicegui？

nicegui：1.4.5![image](https://github.com/user-attachments/assets/f75b5436-3945-4e10-b71a-7954f28310bd)

**Comment by MistEO** [comment]
升级一下 nicegui，我不知道最低可用版本是多少，但我本地是 nicegui 2.1.0，大版本可能加新东西了

**Comment by xiaofeiTM233** [comment]
更新 nicegui 到最新版本就正常了，应该是需要 2.0 以上，感谢
←因为其它项目开发有安装过 nicegui 旧版本所以在新版 MaaDebugger 中使用不正常
