### ISSUE TITLE
MaaDebugger只显示模拟器桌面

### ISSUE THREAD

**Issue by juexin1** [MaaXYZ/MaaDebugger#7]
模拟器已经打开明日方舟了，MaaDebugger页面只显示模拟器桌面，点开设置也不显示设置，只显示桌面

**Comment by juexin1** [comment]
![(27AN7JG8R1W(XQEGE02CPT](https://github.com/MaaXYZ/MaaDebugger/assets/139360197/88e545f9-1ae9-4ba3-a5e1-4559536af176)

**Comment by MistEO** [comment]
把 mumu 设置里的“后台保活”关了

**Comment by juexin1** [comment]
可以了，但测试的时候task显示成功但模拟器没反应，点进去显示not found什么情况

**Comment by MistEO** [comment]
啥样的，看看，你的 json 也发下看看

**Comment by juexin1** [comment]
我技术比较小白，想写一个切换小号刷maa的脚本 0.0

**Comment by juexin1** [comment]
[新建文件夹 .zip](https://github.com/MaaXYZ/MaaDebugger/files/15243289/default.zip)

**Comment by MistEO** [comment]
recognition，你打错了

![image](https://github.com/MaaXYZ/MaaDebugger/assets/18511905/dce639e4-b28f-401f-9f5b-5640095ad3af)

**Comment by juexin1** [comment]
对不起佬＞人＜，我是铸币，今晚在调一下。麻烦了
